from __future__ import annotations
from datetime import datetime, timezone
from typing import List, Dict
from fastapi import APIRouter
from backend.mutualaid.service import get_mutualaid_engine, UTILITY_NETWORK
from backend.assets.fault_detector import fault_detector

ics214_router = APIRouter(prefix="/mutualaid", tags=["Mutual Aid Network"])

def _generate_ics214_html(event_name: str, requesting_utility: str, incident_period: str,
                           resources: List[Dict], activity_log: List[Dict],
                           report_id: str, generated_at: str) -> str:
    resource_rows = "".join([
        f"<tr><td>{r.get('name','')}</td><td>{r.get('ics_position','')}</td>"
        f"<td>{r.get('home_agency','')}</td><td>{r.get('arrived','')}</td>"
        f"<td>{r.get('departed','')}</td></tr>"
        for r in resources
    ])
    activity_rows = "".join([
        f"<tr><td style='white-space:nowrap'>{a.get('time','')}</td>"
        f"<td>{a.get('notable_activities','')}</td></tr>"
        for a in activity_log
    ])
    return f"""<!DOCTYPE html>
<html><head><meta charset='UTF-8'>
<title>ICS 214 - {event_name}</title>
<style>
  body{{font-family:Arial,sans-serif;font-size:11px;margin:20px;color:#000}}
  h1{{font-size:16px;text-align:center;margin:0}}
  h2{{font-size:12px;text-align:center;margin:0 0 10px}}
  .header{{border:2px solid #000;padding:8px;margin-bottom:8px}}
  .form-row{{display:flex;gap:0;margin-bottom:4px}}
  .field{{border:1px solid #000;padding:4px 6px;flex:1}}
  .field-label{{font-weight:bold;font-size:9px;display:block;color:#333}}
  table{{width:100%;border-collapse:collapse;margin-bottom:8px}}
  th{{background:#ddd;border:1px solid #000;padding:4px;font-size:10px;text-align:left}}
  td{{border:1px solid #000;padding:4px;font-size:10px}}
  .section-title{{background:#999;color:#fff;font-weight:bold;padding:3px 6px;margin:8px 0 4px;font-size:11px}}
  .footer{{margin-top:16px;border-top:1px solid #000;padding-top:6px;font-size:9px;color:#666}}
  .gridiq-badge{{background:#0a0f1e;color:#fff;padding:2px 8px;border-radius:3px;font-size:9px}}
</style></head><body>
<div class='header'>
  <h1>ICS 214 — ACTIVITY LOG</h1>
  <h2>National Incident Management System (NIMS)</h2>
  <div class='form-row'>
    <div class='field' style='flex:2'><span class='field-label'>1. INCIDENT NAME</span>{event_name}</div>
    <div class='field'><span class='field-label'>2. OPERATIONAL PERIOD DATE/TIME</span>{incident_period}</div>
    <div class='field'><span class='field-label'>FORM #</span>{report_id}</div>
  </div>
  <div class='form-row'>
    <div class='field' style='flex:2'><span class='field-label'>3. NAME / REQUESTING UTILITY</span>{requesting_utility}</div>
    <div class='field'><span class='field-label'>4. ICS SECTION</span>Operations</div>
    <div class='field'><span class='field-label'>5. DATE / TIME PREPARED</span>{generated_at}</div>
  </div>
</div>

<div class='section-title'>6. RESOURCES ASSIGNED</div>
<table>
  <tr><th>Name</th><th>ICS Position</th><th>Home Agency</th><th>Date/Time Arrived</th><th>Date/Time Departed</th></tr>
  {resource_rows}
</table>

<div class='section-title'>7. ACTIVITY LOG</div>
<table>
  <tr><th style='width:140px'>Date / Time</th><th>Notable Activities</th></tr>
  {activity_rows}
</table>

<div class='section-title'>8. PREPARED BY</div>
<div class='form-row'>
  <div class='field'><span class='field-label'>NAME</span>GridIQ Automated System</div>
  <div class='field'><span class='field-label'>POSITION / TITLE</span>AI Grid Intelligence Platform</div>
  <div class='field'><span class='field-label'>SIGNATURE / SYSTEM</span><span class='gridiq-badge'>GridIQ — gridiq.ink</span></div>
</div>

<div class='footer'>
  Auto-generated by GridIQ — Paradise, CA | Report ID: {report_id} | {generated_at}<br>
  This form complies with NIMS ICS-214 Activity Log requirements per FEMA guidelines.
</div>
</body></html>"""

@ics214_router.get("/ics214", summary="Auto-generate NIMS ICS-214 Activity Log")
async def generate_ics214(utility_name: str = "Demo Utility — Paradise CA"):
    now = datetime.now(timezone.utc)
    faults = fault_detector.get_active_faults()
    engine = get_mutualaid_engine()
    report = engine.generate_report(faults)
    available = [s for s in report.utility_statuses if s.can_send_aid]

    resources = []
    for i, u in enumerate(available[:6]):
        for j in range(min(u.available_crews, 2)):
            resources.append({
                "name": f"Crew {i+1}-{j+1} ({u.utility_name})",
                "ics_position": "Line Crew" if "transmission" in u.specialties else "Distribution Crew",
                "home_agency": u.utility_name,
                "arrived": "",
                "departed": "",
            })

    activity_log = [
        {"time": now.strftime("%Y-%m-%d %H:%M UTC"), "notable_activities": f"ICS-214 auto-generated by GridIQ. {len(faults)} active faults detected on system."},
        {"time": now.strftime("%Y-%m-%d %H:%M UTC"), "notable_activities": f"Mutual aid request issued. {len(available)} utilities available in network."},
    ]
    for f in faults[:5]:
        activity_log.append({
            "time": now.strftime("%Y-%m-%d %H:%M UTC"),
            "notable_activities": f"FAULT: {f.severity.value.upper()} — {f.asset_name}: {f.fault_code}"
        })
    for u in available[:3]:
        activity_log.append({
            "time": now.strftime("%Y-%m-%d %H:%M UTC"),
            "notable_activities": f"Aid confirmed: {u.utility_name} — {u.available_crews} crews available, ETA {u.estimated_response_hours}h"
        })

    html = _generate_ics214_html(
        event_name=f"Grid Emergency — {utility_name}",
        requesting_utility=utility_name,
        incident_period=f"{now.strftime('%Y-%m-%d %H:%M')} UTC — Ongoing",
        resources=resources,
        activity_log=activity_log,
        report_id=f"ICS214-{now.strftime('%Y%m%d-%H%M')}",
        generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
    )

    from fastapi.responses import HTMLResponse
    return HTMLResponse(content=html, status_code=200)

@ics214_router.get("/ics214/data", summary="ICS-214 data as JSON")
async def get_ics214_data(utility_name: str = "Demo Utility — Paradise CA"):
    now = datetime.now(timezone.utc)
    faults = fault_detector.get_active_faults()
    engine = get_mutualaid_engine()
    report = engine.generate_report(faults)
    available = [s for s in report.utility_statuses if s.can_send_aid]
    return {
        "form": "ICS-214",
        "incident_name": f"Grid Emergency — {utility_name}",
        "requesting_utility": utility_name,
        "generated_at": now.isoformat(),
        "operational_period": f"{now.strftime('%Y-%m-%d %H:%M')} UTC — Ongoing",
        "active_faults": len(faults),
        "utilities_responding": len(available[:3]),
        "total_crews_responding": sum(u.available_crews for u in available[:3]),
        "resources_assigned": [
            {"utility": u.utility_name, "crews": u.available_crews,
             "specialties": u.specialties, "eta_hours": u.estimated_response_hours,
             "contact": u.contact}
            for u in available[:6]
        ],
        "activity_log_entries": len(faults) + len(available[:3]) + 2,
        "form_url": f"/api/v1/mutualaid/ics214?utility_name={utility_name.replace(' ', '+')}",
    }
